name = "StructPack"
uuid = "9297859c-0cb3-4368-9f60-4c60e5718164"
authors = ["Thomas Staudt <tscode@posteo.net>"]
version = "0.3.0"

[weakdeps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[extensions]
DatesExt = ["Dates"]

[compat]
Dates = "1.9"
Logging = "1.9"
Random = "1.9"
Test = "1.9"
julia = "1.9"

[extras]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "Logging"]
